name: PR automations
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint-code:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Cache dependencies
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
        with:
          path: '**/node_modules'
          key: ec2-github-runner-${{ hashFiles('**/package-lock.json') }}
      - name: Install packages
        run: npm install
      - name: Run linter
        run: npm run lint
